/**
 * @file types.ts
 *
 * Central TypeScript type definitions for Voyager AI.
 * Shared between API routes (server) and React components (client) to
 * guarantee a single source of truth for all data shapes.
 *
 * Import pattern:
 *   import type { Activity, DayPlan } from "@/lib/types";
 */

// ---------------------------------------------------------------------------
// Itinerary data model
// ---------------------------------------------------------------------------

/**
 * A single activity within a travel day.
 * The `type` union drives icon and colour selection in ItineraryTimeline.
 */
export interface Activity {
  /** Stable unique identifier for React list keys and Firestore references. */
  id: string;
  /** Human-readable time string, e.g. "10:00 AM". */
  time: string;
  /** Short title of the activity. */
  title: string;
  /** 2-3 sentence description with local context, generated by Gemini. */
  description: string;
  /** Activity category — maps to an icon and accent colour in the UI. */
  type: "sightseeing" | "food" | "culture" | "relaxation" | "adventure";
  /** Estimated cost string, e.g. "$20" or "Free". */
  cost: string;
  /** Specific venue or neighbourhood name within the destination city. */
  location?: string;
}

/**
 * A single day's plan, containing an ordered list of activities.
 */
export interface DayPlan {
  /** Human-readable label, e.g. "Day 1". */
  day: string;
  /** Short date string, e.g. "Oct 12". */
  date: string;
  activities: Activity[];
}

// ---------------------------------------------------------------------------
// API request / response contracts
// ---------------------------------------------------------------------------

/**
 * Body sent from the client to POST /api/generate.
 * The Zod schema in validation.ts enforces these constraints at runtime.
 */
export interface GenerateRequest {
  destination: string;
  vibe: string;
  /** Total trip budget in USD. Defaults to $2,500. */
  budget?: number;
  /** Trip length in days (1–14). Defaults to 3. */
  days?: number;
  /** When true, Gemini is instructed to select only wheelchair-accessible venues. */
  wheelchairAccessible?: boolean;
  /** Natural-language refinement instruction from the Experience Engine sidebar. */
  prompt?: string;
  /**
   * The current itinerary, passed during refinements so Gemini can make
   * surgical edits rather than regenerating the entire trip from scratch.
   */
  existingItinerary?: DayPlan[];
}

/** Shape of a successful response from POST /api/generate. */
export interface GenerateResponse {
  itinerary: DayPlan[];
}

// ---------------------------------------------------------------------------
// Firestore data model
// ---------------------------------------------------------------------------

/**
 * A persisted trip document in the Firestore "trips" collection.
 * Saved automatically after each Gemini generation and after each refinement,
 * enabling the shareable collaboration URL.
 */
export interface Trip {
  /** Firestore document ID, also embedded in the document for convenience. */
  id: string;
  destination: string;
  vibe: string;
  budget: number;
  days: number;
  itinerary: DayPlan[];
  /** Unix millisecond timestamp of when the trip was first saved. */
  createdAt: number;
}
